### ISSUE TITLE
issues with the undertale data mirror

### ISSUE THREAD

**Issue by thetrick42** [steviegt6/tomat.dev#20]
the document for papyrus calls has multiple factual mistakes

1. the Undyne call for room_fire_hotelfront_1 says the ELSE text appears if the Royal Guards are spared; that is incorrect. It appears when they are killed (the flag keeping track of it is 402, and if you check for it in the flags section of the mirror, its description is, in fact, correct)
2. the room name for the call from room_tundra_sanshouse is in the table listed as room_tundra_garage (which has no call assigned to it, as you can only access this room prior to defeating Papyrus)
3. the room name for the call from room_tundra_paproom is in the table listed as room_tundra_sanshouse, probably as a consequence of the previous mistake

**Comment by steviegt6** [comment]
make a pr
